### ISSUE TITLE
Split Editor Plug-in does not work in Eclipse Juno (4.2)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sandipchitale/sandipchitaleseclipseplugins#7]
```
What steps will reproduce the problem?
1. Try to split the editor in Eclipse Juno (4.2).

What is the expected output? What do you see instead?
The editor splits. Instead get an exception:

java.lang.NoClassDefFoundError: org/eclipse/ui/internal/PartStack
at spliteditor.Handler$1.partActivated(Handler.java:74)
at org.eclipse.ui.internal.WorkbenchPage$11.run(WorkbenchPage.java:4306)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
at 
org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4304)
at org.eclipse.ui.internal.WorkbenchPage.access$14(WorkbenchPage.java:4292)
at 
org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage
.java:169)
at 
org.eclipse.e4.ui.internal.workbench.PartServiceImpl$2.run(PartServiceImpl.java:
190)


```

Original issue reported on code.google.com by `sandipchitale` on 23 Jul 2012 at 1:32
